/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TripBuilderRouteImport } from './routes/trip-builder'
import { Route as RoutePlannerRouteImport } from './routes/route-planner'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as PlacesRouteImport } from './routes/places'
import { Route as IndexRouteImport } from './routes/index'

const TripBuilderRoute = TripBuilderRouteImport.update({
  id: '/trip-builder',
  path: '/trip-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutePlannerRoute = RoutePlannerRouteImport.update({
  id: '/route-planner',
  path: '/route-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesRoute = PlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/places': typeof PlacesRoute
  '/review': typeof ReviewRoute
  '/route-planner': typeof RoutePlannerRoute
  '/trip-builder': typeof TripBuilderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/places': typeof PlacesRoute
  '/review': typeof ReviewRoute
  '/route-planner': typeof RoutePlannerRoute
  '/trip-builder': typeof TripBuilderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/places': typeof PlacesRoute
  '/review': typeof ReviewRoute
  '/route-planner': typeof RoutePlannerRoute
  '/trip-builder': typeof TripBuilderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/places' | '/review' | '/route-planner' | '/trip-builder'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/places' | '/review' | '/route-planner' | '/trip-builder'
  id:
    | '__root__'
    | '/'
    | '/places'
    | '/review'
    | '/route-planner'
    | '/trip-builder'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlacesRoute: typeof PlacesRoute
  ReviewRoute: typeof ReviewRoute
  RoutePlannerRoute: typeof RoutePlannerRoute
  TripBuilderRoute: typeof TripBuilderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trip-builder': {
      id: '/trip-builder'
      path: '/trip-builder'
      fullPath: '/trip-builder'
      preLoaderRoute: typeof TripBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route-planner': {
      id: '/route-planner'
      path: '/route-planner'
      fullPath: '/route-planner'
      preLoaderRoute: typeof RoutePlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places': {
      id: '/places'
      path: '/places'
      fullPath: '/places'
      preLoaderRoute: typeof PlacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlacesRoute: PlacesRoute,
  ReviewRoute: ReviewRoute,
  RoutePlannerRoute: RoutePlannerRoute,
  TripBuilderRoute: TripBuilderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
