export type {
  SourceType,
  Verification,
  Category,
  Place,
  Workspace,
  UploadStatus,
  AgentName,
  AgentStatus,
  ItineraryStop,
  ItineraryDay,
  ReviewCard,
} from "@/lib/types";

import type {
  AgentName,
  AgentStatus,
  ItineraryDay,
  Place,
  ReviewCard,
  SourceType,
  UploadStatus,
  Workspace,
} from "@/lib/types";

export const workspaces: Workspace[] = [
  {
    id: "jp",
    name: "Japan Autumn",
    flag: "🇯🇵",
    country: "Japan",
    city: "Tokyo",
    destination: "Tokyo, Japan",
  },
  {
    id: "it",
    name: "Italy Summer",
    flag: "🇮🇹",
    country: "Italy",
    city: "Rome",
    destination: "Rome, Italy",
  },
  {
    id: "cn",
    name: "China 2026",
    flag: "🇨🇳",
    country: "China",
    city: "Shanghai",
    destination: "Shanghai, China",
  },
];

const img = (id: string, w = 600, h = 800) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w}&h=${h}&q=80`;

export const places: Place[] = [
  {
    id: "p1",
    title: "Hidden Coffee Roastery",
    city: "Tokyo",
    country: "Japan",
    category: "Cafe",
    tags: ["Minimal", "Coffee Culture", "Slow Travel"],
    source: "Instagram",
    confidence: 0.94,
    verification: "Verified",
    image: img("1495474472287-4d71bcdd2085", 600, 800),
    description:
      "Quiet third-wave roastery tucked in a Nakameguro alley. Hand-drip only, single origin rotation.",
    aestheticNote: "Quiet minimalist café perfect for a slow morning.",
    reason: "Matches your Coffee Culture and Minimal preferences.",
    height: 320,
  },
  {
    id: "p2",
    title: "teamLab Planets",
    city: "Tokyo",
    country: "Japan",
    category: "Museum",
    tags: ["Neon", "Photography", "Creative"],
    source: "Pinterest",
    confidence: 0.97,
    verification: "Verified",
    image: img("1480796927426-f609979314bd", 600, 700),
    description:
      "Immersive digital art museum in Toyosu. Barefoot installations across mirrored water rooms.",
    aestheticNote: "Otherworldly light environments — book the evening slot.",
    reason: "You pinned 3 immersive art spaces this week.",
    height: 280,
  },
  {
    id: "p3",
    title: "Yanaka Ginza",
    city: "Tokyo",
    country: "Japan",
    category: "Neighborhood",
    tags: ["Vintage", "Hidden Gem", "Slow Travel"],
    source: "Article",
    confidence: 0.88,
    verification: "Verified",
    image: img("1528360983277-13d401cdc186", 600, 800),
    description:
      "Old Shitamachi shopping street with senbei shops, alley cats, and pre-war wooden facades.",
    aestheticNote: "Golden-hour light, terracotta rooftops, slow stroll.",
    reason: "Walkable and matches your Hidden Gems mood.",
    height: 340,
  },
  {
    id: "p4",
    title: "Aoyama Flower Market Tea House",
    city: "Tokyo",
    country: "Japan",
    category: "Cafe",
    tags: ["Cozy", "Photography"],
    source: "Pinterest",
    confidence: 0.91,
    verification: "Verified",
    image: img("1554118811-1e0d58224f24", 600, 700),
    description: "Greenhouse café surrounded by florist arrangements. Try the fruit parfait.",
    aestheticNote: "A botanical pocket inside the city.",
    reason: "Adds visual variety to your café crawl.",
    height: 260,
  },
  {
    id: "p5",
    title: "Nezu Museum Garden",
    city: "Tokyo",
    country: "Japan",
    category: "Park",
    tags: ["Architecture", "Slow Travel"],
    source: "Pinterest",
    confidence: 0.93,
    verification: "Verified",
    image: img("1545569341-9eb8b30979d9", 600, 800),
    description:
      "Kuma Kengo-designed museum with a tucked-away strolling garden of stone lanterns.",
    aestheticNote: "Mossy quiet — best on a weekday morning.",
    reason: "You bookmarked 2 Kuma projects.",
    height: 330,
  },
  {
    id: "p6",
    title: "Daikanyama T-Site",
    city: "Tokyo",
    country: "Japan",
    category: "Shopping",
    tags: ["Architecture", "Minimal"],
    source: "Instagram",
    confidence: 0.9,
    verification: "Verified",
    image: img("1542051841857-5f90071e7989", 600, 700),
    description:
      "Tsutaya bookstore complex — woven-facade architecture, design magazine selection.",
    aestheticNote: "Lattice shadows across the courtyard at dusk.",
    reason: "Pairs with nearby cafés on your saved list.",
    height: 280,
  },
  {
    id: "p7",
    title: "Omoide Yokocho",
    city: "Tokyo",
    country: "Japan",
    category: "Restaurant",
    tags: ["Neon", "Vintage"],
    source: "Screenshot",
    confidence: 0.82,
    verification: "Needs Recheck",
    image: img("1554797589-7241bb691973", 600, 800),
    description: "Postwar alley of tiny yakitori counters under tangled cables and red lanterns.",
    aestheticNote: "Smoke, neon, and shoulder-to-shoulder seats.",
    reason: "Anchor for your neon evening route.",
    height: 320,
  },
  {
    id: "p8",
    title: "Shibuya Sky",
    city: "Tokyo",
    country: "Japan",
    category: "Viewpoint",
    tags: ["Photography"],
    source: "Pinterest",
    confidence: 0.95,
    verification: "Verified",
    image: img("1540959733332-eab4deabeeaf", 600, 700),
    description:
      "Open-air rooftop observatory above the Shibuya scramble. Sunset slots sell out fast.",
    aestheticNote: "Golden hour onto blue hour, all in one window.",
    reason: "Your saved viewpoints favor sunset slots.",
    height: 280,
  },
  {
    id: "p9",
    title: "Onibus Coffee Nakameguro",
    city: "Tokyo",
    country: "Japan",
    category: "Cafe",
    tags: ["Coffee Culture", "Minimal"],
    source: "Instagram",
    confidence: 0.86,
    verification: "Unverified",
    image: img("1453614512568-c4024d13c247", 600, 800),
    description:
      "Two-floor specialty café beside the train tracks. Window seat, espresso, train rumble.",
    aestheticNote: "Trains pass like a slow metronome.",
    reason: "Top match for your Coffee Crawl style.",
    height: 340,
  },
  {
    id: "p10",
    title: "Meiji Jingu Forest Path",
    city: "Tokyo",
    country: "Japan",
    category: "Park",
    tags: ["Slow Travel", "Hidden Gem"],
    source: "Article",
    confidence: 0.92,
    verification: "Verified",
    image: img("1528164344705-47542687000d", 600, 700),
    description:
      "Hand-planted urban forest leading to the Meiji shrine. Torii gates and cedar quiet.",
    aestheticNote: "Cathedral hush, dappled light.",
    reason: "Balances dense days with green space.",
    height: 280,
  },
  {
    id: "p11",
    title: "Higashiya Ginza",
    city: "Tokyo",
    country: "Japan",
    category: "Cafe",
    tags: ["Minimal", "Slow Travel"],
    source: "Pinterest",
    confidence: 0.89,
    verification: "Verified",
    image: img("1517248135467-4c7edcad34c4", 600, 800),
    description: "Modern wagashi salon — seasonal sweets and koicha in a small tearoom.",
    aestheticNote: "Cedar, paper, single chrysanthemum.",
    reason: "Quiet afternoon stop on your Ginza day.",
    height: 320,
  },
  {
    id: "p12",
    title: "Tsukiji Outer Market",
    city: "Tokyo",
    country: "Japan",
    category: "Market",
    tags: ["Photography", "Hidden Gem"],
    source: "Article",
    confidence: 0.84,
    verification: "Needs Recheck",
    image: img("1583224964978-2257b960c3d3", 600, 700),
    description: "Early-morning food stalls — tamagoyaki, uni rice bowls, knife shops.",
    aestheticNote: "Steam, shouts, neat rows of fish.",
    reason: "Anchors a market morning route.",
    height: 280,
  },
];

export const uploads = [
  {
    id: "u1",
    title: "Tokyo café — Instagram screenshot",
    source: "Instagram" as SourceType,
    time: "2m ago",
    status: "Extracting places" as UploadStatus,
    progress: 62,
    image: img("1511920170033-f8396924c348", 400, 400),
    note: "love the wood counter",
  },
  {
    id: "u2",
    title: "Pinterest pin — minimalist architecture",
    source: "Pinterest" as SourceType,
    time: "12m ago",
    status: "Classifying categories" as UploadStatus,
    progress: 84,
    image: img("1554118811-1e0d58224f24", 400, 400),
    note: "",
  },
  {
    id: "u3",
    title: "Article — hidden Tokyo neighborhoods",
    source: "Article" as SourceType,
    time: "1h ago",
    status: "Completed" as UploadStatus,
    progress: 100,
    image: img("1528360983277-13d401cdc186", 400, 400),
    note: "save Yanaka section",
  },
  {
    id: "u4",
    title: "Screenshot — café with unknown address",
    source: "Screenshot" as SourceType,
    time: "3h ago",
    status: "Fallback / Needs manual review" as UploadStatus,
    progress: 100,
    image: img("1453614512568-c4024d13c247", 400, 400),
    note: "",
  },
  {
    id: "u5",
    title: "Pinterest board — Japan autumn moodboard",
    source: "Pinterest" as SourceType,
    time: "yesterday",
    status: "Awaiting review" as UploadStatus,
    progress: 100,
    image: img("1545569341-9eb8b30979d9", 400, 400),
    note: "",
  },
];

export const agentTimeline = [
  {
    id: "a1",
    agent: "Supervisor Agent" as AgentName,
    time: "just now",
    status: "Success" as AgentStatus,
    summary: "Started itinerary planning for Tokyo, 4 days.",
    confidence: 0.98,
    tools: ["plan_route", "delegate_task"],
    input: "workspace=jp, days=4, style=Aesthetic",
    output: "Delegated to Curator → Researcher → Planner.",
  },
  {
    id: "a2",
    agent: "Curator Agent" as AgentName,
    time: "1m ago",
    status: "Success" as AgentStatus,
    summary: "Extracted 12 places from recent uploads.",
    confidence: 0.91,
    tools: ["parse_link", "ocr_image", "extract_places"],
    input: "uploads=5",
    output: "12 places, 9 verified, 3 awaiting review.",
  },
  {
    id: "a3",
    agent: "Researcher Agent" as AgentName,
    time: "2m ago",
    status: "Success" as AgentStatus,
    summary: "Verified opening hours and locations.",
    confidence: 0.88,
    tools: ["geocode_place", "verify_place_status", "rag_search"],
    input: "12 places",
    output: "10 verified, 2 flagged for recheck. RAG retrieved 4 similar places.",
  },
  {
    id: "a4",
    agent: "Planner Agent" as AgentName,
    time: "3m ago",
    status: "Success" as AgentStatus,
    summary: "Generated 4-day Tokyo route grouped by neighborhood.",
    confidence: 0.93,
    tools: ["cluster_geo", "rag_search", "score_route"],
    input: "16 candidates",
    output: "4 days × 4 stops, walkable clusters.",
  },
  {
    id: "a5",
    agent: "Verifier Agent" as AgentName,
    time: "4m ago",
    status: "Needs Review" as AgentStatus,
    summary: "Merged 2 duplicates, flagged 1 place for review.",
    confidence: 0.79,
    tools: ["merge_duplicates", "verify_place_status"],
    input: "route + KB",
    output: "Blue Bottle Shibuya ↔ Blue Bottle Coffee merged. 1 closed-place flag.",
  },
  {
    id: "a6",
    agent: "Researcher Agent" as AgentName,
    time: "5m ago",
    status: "Fallback" as AgentStatus,
    summary: "Web verification unavailable — place saved as Unverified.",
    confidence: 0.55,
    tools: ["verify_place_status"],
    input: "Onibus Coffee Nakameguro",
    output: "Saved as Unverified, will retry later.",
  },
];

export const itinerary: ItineraryDay[] = [
  {
    day: 1,
    theme: "Slow Morning, Neon Evening",
    stops: [
      {
        n: 1,
        time: "08:30",
        title: "Hidden Coffee Roastery",
        category: "Cafe",
        district: "Nakameguro",
        travelNote: "5 min walk from station",
        aestheticNote: "Quiet minimalist café perfect for a slow morning.",
        reason: "Matches your Coffee Culture and Minimal preferences.",
        source: "Saved",
        verification: "Verified",
        mood: "Slow Morning Coffee",
        image: img("1495474472287-4d71bcdd2085", 400, 300),
      },
      {
        n: 2,
        time: "10:30",
        title: "Daikanyama T-Site",
        category: "Shopping",
        district: "Daikanyama",
        travelNote: "12 min walk along canal",
        aestheticNote: "Lattice shadows across the courtyard.",
        reason: "Adjacent neighborhood — keeps morning walkable.",
        source: "Saved",
        verification: "Verified",
        mood: "Architecture Walk",
        image: img("1542051841857-5f90071e7989", 400, 300),
      },
      {
        n: 3,
        time: "14:00",
        title: "Nezu Museum Garden",
        category: "Park",
        district: "Aoyama",
        travelNote: "Hibiya Line to Omotesando",
        aestheticNote: "Mossy quiet — weekday best.",
        reason: "Architecture preference + green space pacing.",
        source: "RAG Similar",
        verification: "Verified",
        mood: "Hidden Courtyard",
        image: img("1545569341-9eb8b30979d9", 400, 300),
      },
      {
        n: 4,
        time: "19:00",
        title: "Omoide Yokocho",
        category: "Restaurant",
        district: "Shinjuku",
        travelNote: "Yamanote Line, 18 min",
        aestheticNote: "Smoke, neon, shoulder-to-shoulder.",
        reason: "Anchor for your neon evening mood.",
        source: "Saved",
        verification: "Needs Recheck",
        mood: "Neon Evening",
        image: img("1554797589-7241bb691973", 400, 300),
      },
    ],
  },
  {
    day: 2,
    theme: "Forest & Sky",
    stops: [
      {
        n: 1,
        time: "09:00",
        title: "Meiji Jingu Forest Path",
        category: "Park",
        district: "Harajuku",
        travelNote: "From Harajuku Station",
        aestheticNote: "Cathedral hush, dappled light.",
        reason: "Balances dense days with green.",
        source: "Saved",
        verification: "Verified",
        mood: "Golden Hour Walk",
        image: img("1528164344705-47542687000d", 400, 300),
      },
      {
        n: 2,
        time: "12:30",
        title: "Aoyama Flower Market Tea House",
        category: "Cafe",
        district: "Omotesando",
        travelNote: "15 min walk",
        aestheticNote: "Botanical pocket in the city.",
        reason: "Cozy + photogenic stop.",
        source: "Saved",
        verification: "Verified",
        mood: "Botanical Lunch",
        image: img("1554118811-1e0d58224f24", 400, 300),
      },
      {
        n: 3,
        time: "16:00",
        title: "Shibuya Sky",
        category: "Viewpoint",
        district: "Shibuya",
        travelNote: "2 stops on Ginza Line",
        aestheticNote: "Golden hour to blue hour.",
        reason: "You favor sunset viewpoints.",
        source: "Verified Recommendation",
        verification: "Verified",
        mood: "Sunset View",
        image: img("1540959733332-eab4deabeeaf", 400, 300),
      },
      {
        n: 4,
        time: "20:00",
        title: "Onibus Coffee Nakameguro",
        category: "Cafe",
        district: "Nakameguro",
        travelNote: "Tokyu Toyoko Line",
        aestheticNote: "Trains as a slow metronome.",
        reason: "Wind-down espresso, train window seat.",
        source: "RAG Similar",
        verification: "Unverified",
        mood: "Quiet Wind-Down",
        image: img("1453614512568-c4024d13c247", 400, 300),
      },
    ],
  },
  {
    day: 3,
    theme: "Shitamachi & Old Tokyo",
    stops: [
      {
        n: 1,
        time: "09:30",
        title: "Yanaka Ginza",
        category: "Neighborhood",
        district: "Yanaka",
        travelNote: "Nippori Station",
        aestheticNote: "Golden-hour light, terracotta rooftops.",
        reason: "Hidden Gems + walkable.",
        source: "Saved",
        verification: "Verified",
        mood: "Old Tokyo Stroll",
        image: img("1528360983277-13d401cdc186", 400, 300),
      },
      {
        n: 2,
        time: "12:00",
        title: "Higashiya Ginza",
        category: "Cafe",
        district: "Ginza",
        travelNote: "Hibiya Line, 22 min",
        aestheticNote: "Cedar, paper, single chrysanthemum.",
        reason: "Quiet afternoon stop.",
        source: "Saved",
        verification: "Verified",
        mood: "Tea & Wagashi",
        image: img("1517248135467-4c7edcad34c4", 400, 300),
      },
      {
        n: 3,
        time: "15:00",
        title: "teamLab Planets",
        category: "Museum",
        district: "Toyosu",
        travelNote: "Yurakucho Line",
        aestheticNote: "Otherworldly light environments.",
        reason: "Creative + Photography preferences.",
        source: "Saved",
        verification: "Verified",
        mood: "Immersive Light",
        image: img("1480796927426-f609979314bd", 400, 300),
      },
    ],
  },
  {
    day: 4,
    theme: "Market Morning",
    stops: [
      {
        n: 1,
        time: "07:00",
        title: "Tsukiji Outer Market",
        category: "Market",
        district: "Tsukiji",
        travelNote: "Hibiya Line",
        aestheticNote: "Steam, shouts, neat fish rows.",
        reason: "Anchors a market morning.",
        source: "Saved",
        verification: "Needs Recheck",
        mood: "Market Morning",
        image: img("1583224964978-2257b960c3d3", 400, 300),
      },
      {
        n: 2,
        time: "11:00",
        title: "Hama-rikyu Gardens",
        category: "Park",
        district: "Shiodome",
        travelNote: "10 min walk from Tsukiji",
        aestheticNote: "Tidal pond, tea pavilion.",
        reason: "RAG: similar to Nezu Garden.",
        source: "RAG Similar",
        verification: "Verified",
        mood: "Tidal Calm",
        image: img("1545569341-9eb8b30979d9", 400, 300),
      },
      {
        n: 3,
        time: "14:30",
        title: "Ginza Six Rooftop",
        category: "Viewpoint",
        district: "Ginza",
        travelNote: "20 min walk",
        aestheticNote: "Open-sky garden above shopping.",
        reason: "Verified web recommendation.",
        source: "Verified Recommendation",
        verification: "Verified",
        mood: "Rooftop Pause",
        image: img("1540959733332-eab4deabeeaf", 400, 300),
      },
    ],
  },
];

export const reviewQueue: ReviewCard[] = [
  {
    id: "r1",
    type: "Duplicate place detected",
    title: "Blue Bottle Shibuya vs Blue Bottle Coffee",
    city: "Tokyo",
    country: "Japan",
    category: "Cafe",
    confidence: 0.92,
    explanation:
      "Two extractions point to the same coordinates within 30m. Likely the same location with different naming conventions.",
    source: "Pinterest",
    suggestedAction: "Merge Duplicate",
    image: img("1453614512568-c4024d13c247", 400, 300),
  },
  {
    id: "r2",
    type: "Low confidence extraction",
    title: "Unnamed café from Instagram screenshot",
    city: "Tokyo?",
    country: "Japan",
    category: "Cafe",
    confidence: 0.41,
    explanation: "OCR could not resolve a venue name. Closest visual match via RAG: Fuglen Tokyo.",
    source: "Screenshot",
    suggestedAction: "Edit",
    image: img("1511920170033-f8396924c348", 400, 300),
  },
  {
    id: "r3",
    type: "Possible closed/outdated place",
    title: "Bear Pond Espresso",
    city: "Tokyo",
    country: "Japan",
    category: "Cafe",
    confidence: 0.68,
    explanation:
      "Web verification returned conflicting opening hours. Recommend manual recheck before adding to route.",
    source: "Article",
    suggestedAction: "Confirm",
    image: img("1495474472287-4d71bcdd2085", 400, 300),
  },
  {
    id: "r4",
    type: "Missing category",
    title: "Tokyo Photographers' Gallery",
    city: "Tokyo",
    country: "Japan",
    category: "Other",
    confidence: 0.74,
    explanation:
      "Extraction succeeded but category classifier was unsure between Museum and Gallery.",
    source: "Pinterest",
    suggestedAction: "Edit",
    image: img("1542051841857-5f90071e7989", 400, 300),
  },
  {
    id: "r5",
    type: "Search unavailable — saved as draft",
    title: "Kissa You Ginza",
    city: "Tokyo",
    country: "Japan",
    category: "Cafe",
    confidence: 0.6,
    explanation:
      "Verification tool was unavailable. Saved as Unverified draft, will retry on next sync.",
    source: "Instagram",
    suggestedAction: "Confirm",
    image: img("1517248135467-4c7edcad34c4", 400, 300),
  },
];

export const preferences = [
  "Likes coffee shops",
  "Prefers walkable routes",
  "Interested in architecture",
  "Enjoys hidden local places",
  "Loves aesthetic photography spots",
];
